### ISSUE TITLE
Where are the Demo / Example code??

### ISSUE THREAD

**Issue by TigerZhao007** [manlius/muxViz#20]
“To speed up your interaction with muxViz, the folder standalone contains some self-explanatory example scripts which show how to use the most salient analytical techniques available in the library:
community_detection.R
connected_components.R
example_coverage_optimized.R
example_coverage.R
example_overlapping_generator.R
example_plot_edgecolored_heatmap_6panels.R
example_plot_edgecolored_paths_coupling.R
example_plot_edgecolored_paths.R
example_plot_edgecolored.R
example_transitivity_new.R
layer-layer_corr.R
multi_motifs.R”

Where are they???

**Comment by TigerZhao007** [comment]
It seems this project is update now. So let's wait.

**Comment by gbertagnolli** [comment]
Hi @TigerZhao007 thanks for writing. We just updated the repo, adding both [examples scripts](https://github.com/manlius/muxViz/tree/master/examples-scripts) and a cuople of [vignettes](http://manlius.github.io/muxViz/articles/).

**Comment by gbertagnolli** [comment]
Hi @TigerZhao007 thanks for writing. We just updated the repo, adding both [examples scripts](https://github.com/manlius/muxViz/tree/master/examples-scripts) and a cuople of [vignettes](http://manlius.github.io/muxViz/articles/).
