### ISSUE TITLE
could not find function

### ISSUE THREAD

**Issue by TigerZhao007** [manlius/muxViz#22]
muxViz/examples-scripts/example_coverage_optimized.R

Line 104:

    cov.mul.appr <- GetCoverageEvolutionEdgeColored(T.mux, Layers, Nodes, TAUS, Approximate=T, Approximate.disconnected=DisconnectedNodes)

Error in GetCoverageEvolutionEdgeColored(T.mux, Layers, Nodes, TAUS, Approximate = T,  : 
  could not find function "GetCoverageEvolutionEdgeColored"

Some similar "could not find function" problem happened in `example_coverage.R` and `example_overlapping_generator.R`

**Comment by gbertagnolli** [comment]
The issue has been solved, the function `GetCoverageEvolutionEdgeColored` was not expored correctly.
